language: node_js
node_js:
- '0.10'
before_script:
- npm install -g casperjs
- node server.js &
script:
- npm test
env:
  global:
  - secure: F10SusWcW7eGm8sMORcKT7FlrKzgZo2Fc1KlZA3zMx09QRBFZ6Z2vus8y5uPb5x4xzQrVxRKBlf5b+M2aOGH3K2DHW895qznjXuORd7YOrhJFzbFr9s8kGIgW49sL7uIUrz8GVbpO7aLoEt/6fYQHd6Y+X6GBuPwIOonP/UgPAs=
  - secure: fUF7Lvw0ARVQLSQMdyb/NESC73Ms81AW5hgtLLwncTyKYj124sBEtJ6kEQ/rbNN+pB4gEToaolm7uTmefYe3ROBisA+luOcU3HrhAg4JYmGWx3DMuvlWV4F/Hn3YWIBINM8p6z0GAe64MQSEvILkJ4pElxOQcsGHiBgjal12mh4=
  - secure: ZSfR9qHaJ3UMkKJdvaFfqFl3GMHleTJkJ0KIXBOKn8Irx/s5laZehKIHPl/3yyScz98zahsdZR6JBeiPuTOcjnO4WYSb1sMvlBTyhajOqAeMIpq5VCiRt6Qi+saLPHHGm4ntnJSWvV73luslPA9nwGdgwR1hwg7KwyoWJEEqme8=
